### ISSUE TITLE
kube-proxy 工作模式分析中snat

### ISSUE THREAD

**Issue by JasonRD** [kidlj/site#1]
MASQUERADE 是一种更健壮的 SNAT，即将封包的源地址由后端的 endpoint 变更为 Cluster IP。
------------
应该是node ip吧

**Comment by kidlj** [comment]
@JasonRD 对不起，现在才看到。这篇文章满是错误（很多很多），因为当时理解得有问题，有时间我读下 kube-proxy 的源码再来修复下。感谢！

暂时先把这篇文章下架了。
