### ISSUE TITLE
关于ingress nginx issue #3952的问题咨询

### ISSUE THREAD

**Issue by XionZhao** [kidlj/site#2]
你好, [#3952](https://github.com/kubernetes/ingress-nginx/issues/3952) 中提到的问题是否解决了呢，我们在k8s环境中也遇到了

**Comment by kidlj** [comment]
> 你好, [#3952](https://github.com/kubernetes/ingress-nginx/issues/3952) 中提到的问题是否解决了呢，我们在k8s环境中也遇到了

不好意思，才看到这个 issue，忘记 watch 这个 repo 了。就像开发者在那个 issue 里回答的一样，灰度发布的特性在 ingress-nginx 里不受重视，而且根据我阅读其灰度的代码实现后发现，ingress-nginx 的灰度发布功能很受限，而且实现有问题。究其根本，是因为 Ingress 对象本身不支持灰度发布特性（一个 path 只能对应一个 service），Nginx 实现起来也比较麻烦，需要借助 Lua。原生支持灰度发布的负载均衡器和负载中间件可以参考 Envoy 和基于 Envoy 的 Istio（https://istio.io/latest/blog/2017/0.1-canary/）。

因此不太建议使用 ingress-nginx 的灰度发布功能。

**Comment by XionZhao** [comment]
了解，感谢回复，因为延迟原因，我们没办法采用istio等组件
